export const SELECT_CURRENCY = 'GENERAL_CONVERTER/SELECT_CURRENCY';
export const SET_CURRENCY_ITEMS = 'GENERAL_CONVERTER/SET_CURRENCY_ITEMS';
export const SET_LOADED = 'GENERAL_CONVERTER/SET_LOADED';
export const SAGA_SET_CURRENCY_ITEMS =
  'GENERAL_CONVERTER/SAGA_SET_CURRENCY_ITEMS';
