export const SELECT_CURRENCY_GET = 'DETAILED_CONVERTER/SELECT_CURRENCY_GET';
export const SET_PAIR_EXCHANGE = 'DETAILED_CONVERTER/SET_PAIR_EXCHANGE';
export const SET_INPUT_CHANGING = 'DETAILED_CONVERTER/SET_INPUT_CHANGING';
export const SET_INPUT_GET = 'DETAILED_CONVERTER/SET_INPUT_GET';
export const SAGA_SET_PAIR_EXCHANGE =
  'GENERAL_CONVERTER/SAGA_SET_PAIR_EXCHANGE';
