export const SELECT_CURRENCY_GET = 'SELECT_CURRENCY_GET';
export const SET_PAIR_EXCHANGE = 'SET_PAIR_EXCHANGE';
export const SET_INPUT_CHANGING = 'SET_INPUT_CHANGING';
export const SET_INPUT_GET = 'SET_INPUT_GET';
